/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import * as THREE from "three";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Batman({
    entryAnimation,
    loopAnimation,
    ...props
}) {
    const group = useRef();

    const { nodes, materials, animations } = useGLTF("/models/Batman.glb");

    const { actions, names } = useAnimations(animations, group);

    useEffect(() => {
        if (!actions || !entryAnimation) return;

        console.log("Available animations:", names);
        console.log("Playing:", entryAnimation, "→", loopAnimation);

        // Stop all currently playing animations
        Object.values(actions).forEach((action) => {
            if (!action) return;

            action.stop();
            action.reset();
        });

        const entry = actions[entryAnimation];
        const loop = actions[loopAnimation];

        if (!entry) {
            console.warn(`Animation "${entryAnimation}" not found.`);
            return;
        }

        // Configure entry animation
        entry.reset();
        entry.setLoop(THREE.LoopOnce, 1);
        entry.clampWhenFinished = true;
        entry.fadeIn(0.3);
        entry.play();

        const mixer = entry.getMixer();

        const handleFinished = (event) => {
            if (event.action !== entry) return;

            if (loop) {
                loop.reset();
                loop.setLoop(THREE.LoopRepeat, Infinity);
                loop.clampWhenFinished = false;
                loop.fadeIn(0.3);
                loop.play();
            }
        };

        mixer.addEventListener("finished", handleFinished);

        return () => {
            mixer.removeEventListener("finished", handleFinished);

            Object.values(actions).forEach((action) => {
                if (!action) return;

                action.fadeOut(0.2);
                action.stop();
            });
        };
    }, [actions, names, entryAnimation, loopAnimation]);

    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="GLTF_created_0" scale={0.594}>
                    <primitive object={nodes.GLTF_created_0_rootJoint} />
                </group>

                <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Batman_mat}
                    skeleton={nodes.Object_7.skeleton}
                    scale={0.594}
                />

                <group name="GLTF_created_1" scale={0.594}>
                    <primitive object={nodes.GLTF_created_1_rootJoint} />
                </group>

                <skinnedMesh
                    name="Object_400"
                    geometry={nodes.Object_400.geometry}
                    material={materials.Batman_mat}
                    skeleton={nodes.Object_400.skeleton}
                    scale={0.594}
                />
            </group>
        </group>
    );
}

export default Batman;

useGLTF.preload("/models/Batman.glb");